rules:
    default:
        protection:
            required_pull_request_reviews:
                required_approving_review_count: 2
                dismiss_stale_reviews: true
            required_status_checks:
                contexts:
                - continuous-integration/travis-ci
        enabling_label: null
        disabling_label: no-mergify
        disabling_files:
        - .mergify.yml
        - .travis.yml
    branches:
        ^feature/.*:
            protection:
                required_pull_request_reviews:
                    required_approving_review_count: 1
        master: null

